//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class TLTEntities2 : DbContext
{
    public TLTEntities2()
        : base("name=TLTEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tbl_leave_details> tbl_leave_details { get; set; }
    public virtual DbSet<tbl_task_details> tbl_task_details { get; set; }
    public virtual DbSet<tbl_user_roles> tbl_user_roles { get; set; }
    public virtual DbSet<tbl_user_details> tbl_user_details { get; set; }

    public virtual ObjectResult<sp_all_tbl_leave_details_Result> sp_all_tbl_leave_details(Nullable<int> leaveId, string leavedesc, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string appliedBy, string leaveType, string status, string action)
    {
        var leaveIdParameter = leaveId.HasValue ?
            new ObjectParameter("LeaveId", leaveId) :
            new ObjectParameter("LeaveId", typeof(int));

        var leavedescParameter = leavedesc != null ?
            new ObjectParameter("Leavedesc", leavedesc) :
            new ObjectParameter("Leavedesc", typeof(string));

        var fromDateParameter = fromDate.HasValue ?
            new ObjectParameter("FromDate", fromDate) :
            new ObjectParameter("FromDate", typeof(System.DateTime));

        var toDateParameter = toDate.HasValue ?
            new ObjectParameter("ToDate", toDate) :
            new ObjectParameter("ToDate", typeof(System.DateTime));

        var appliedByParameter = appliedBy != null ?
            new ObjectParameter("AppliedBy", appliedBy) :
            new ObjectParameter("AppliedBy", typeof(string));

        var leaveTypeParameter = leaveType != null ?
            new ObjectParameter("LeaveType", leaveType) :
            new ObjectParameter("LeaveType", typeof(string));

        var statusParameter = status != null ?
            new ObjectParameter("Status", status) :
            new ObjectParameter("Status", typeof(string));

        var actionParameter = action != null ?
            new ObjectParameter("Action", action) :
            new ObjectParameter("Action", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_all_tbl_leave_details_Result>("sp_all_tbl_leave_details", leaveIdParameter, leavedescParameter, fromDateParameter, toDateParameter, appliedByParameter, leaveTypeParameter, statusParameter, actionParameter);
    }

    public virtual ObjectResult<sp_all_tbl_task_details_Result> sp_all_tbl_task_details(Nullable<int> taskId, string taskdesc, Nullable<System.DateTime> created_Date, Nullable<System.DateTime> expiry_Date, string createdBy, string assignedTo, string status, string action)
    {
        var taskIdParameter = taskId.HasValue ?
            new ObjectParameter("TaskId", taskId) :
            new ObjectParameter("TaskId", typeof(int));

        var taskdescParameter = taskdesc != null ?
            new ObjectParameter("Taskdesc", taskdesc) :
            new ObjectParameter("Taskdesc", typeof(string));

        var created_DateParameter = created_Date.HasValue ?
            new ObjectParameter("Created_Date", created_Date) :
            new ObjectParameter("Created_Date", typeof(System.DateTime));

        var expiry_DateParameter = expiry_Date.HasValue ?
            new ObjectParameter("Expiry_Date", expiry_Date) :
            new ObjectParameter("Expiry_Date", typeof(System.DateTime));

        var createdByParameter = createdBy != null ?
            new ObjectParameter("CreatedBy", createdBy) :
            new ObjectParameter("CreatedBy", typeof(string));

        var assignedToParameter = assignedTo != null ?
            new ObjectParameter("AssignedTo", assignedTo) :
            new ObjectParameter("AssignedTo", typeof(string));

        var statusParameter = status != null ?
            new ObjectParameter("Status", status) :
            new ObjectParameter("Status", typeof(string));

        var actionParameter = action != null ?
            new ObjectParameter("Action", action) :
            new ObjectParameter("Action", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_all_tbl_task_details_Result>("sp_all_tbl_task_details", taskIdParameter, taskdescParameter, created_DateParameter, expiry_DateParameter, createdByParameter, assignedToParameter, statusParameter, actionParameter);
    }

    public virtual ObjectResult<sp_all_tbl_user_details_Result> sp_all_tbl_user_details(string ntid, string firstName, string lastName, string roleId, string phoneNo, string emailId, string password, string action)
    {
        var ntidParameter = ntid != null ?
            new ObjectParameter("Ntid", ntid) :
            new ObjectParameter("Ntid", typeof(string));

        var firstNameParameter = firstName != null ?
            new ObjectParameter("FirstName", firstName) :
            new ObjectParameter("FirstName", typeof(string));

        var lastNameParameter = lastName != null ?
            new ObjectParameter("LastName", lastName) :
            new ObjectParameter("LastName", typeof(string));

        var roleIdParameter = roleId != null ?
            new ObjectParameter("RoleId", roleId) :
            new ObjectParameter("RoleId", typeof(string));

        var phoneNoParameter = phoneNo != null ?
            new ObjectParameter("PhoneNo", phoneNo) :
            new ObjectParameter("PhoneNo", typeof(string));

        var emailIdParameter = emailId != null ?
            new ObjectParameter("EmailId", emailId) :
            new ObjectParameter("EmailId", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("Password", password) :
            new ObjectParameter("Password", typeof(string));

        var actionParameter = action != null ?
            new ObjectParameter("Action", action) :
            new ObjectParameter("Action", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_all_tbl_user_details_Result>("sp_all_tbl_user_details", ntidParameter, firstNameParameter, lastNameParameter, roleIdParameter, phoneNoParameter, emailIdParameter, passwordParameter, actionParameter);
    }

    public virtual ObjectResult<sp_all_tbl_user_roles_Result> sp_all_tbl_user_roles(string roleId, string roleDesc, string rights, string action)
    {
        var roleIdParameter = roleId != null ?
            new ObjectParameter("RoleId", roleId) :
            new ObjectParameter("RoleId", typeof(string));

        var roleDescParameter = roleDesc != null ?
            new ObjectParameter("RoleDesc", roleDesc) :
            new ObjectParameter("RoleDesc", typeof(string));

        var rightsParameter = rights != null ?
            new ObjectParameter("Rights", rights) :
            new ObjectParameter("Rights", typeof(string));

        var actionParameter = action != null ?
            new ObjectParameter("Action", action) :
            new ObjectParameter("Action", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_all_tbl_user_roles_Result>("sp_all_tbl_user_roles", roleIdParameter, roleDescParameter, rightsParameter, actionParameter);
    }
}
