//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.DEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_task_details
    {
        public int TaskId { get; set; }
        public string Taskdesc { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }
        public string Status { get; set; }
    
        public virtual tbl_user_details tbl_user_details { get; set; }
        public virtual tbl_user_details tbl_user_details1 { get; set; }
    }
}
