//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.DEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_roles
    {
        public tbl_user_roles()
        {
            this.tbl_user_details = new HashSet<tbl_user_details>();
        }
    
        public string RoleId { get; set; }
        public string RoleDesc { get; set; }
        public string Rights { get; set; }
    
        public virtual ICollection<tbl_user_details> tbl_user_details { get; set; }
    }
}
