//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.DEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_leave_details
    {
        public int LeaveId { get; set; }
        public string Leavedesc { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string AppliedBy { get; set; }
        public string LeaveType { get; set; }
        public string Status { get; set; }
    
        public virtual tbl_user_details tbl_user_details { get; set; }
    }
}
